### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by Juice113** [bezirganyan/m2-mixer#6]
sorry to bother you but i tried different versions of pytorch but failed to reimplement the code. So i wonder what the torch version is. thanks very much！
some kinds of error information like this

```
File "/home/xzy/miniconda3/envs/wdw/lib/python3.10/site packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'
(when using torch version 2.0.0)
```

**Comment by bezirganyan** [comment]
Hi @Juice113, 

Thanks for the issue, I just pushed a new `requirements.txt` file, where the versions of packages are fixed. Please try to install packages using this `requirements.txt` file, and let me know if you will have an issue.

**Comment by bezirganyan** [comment]
Hi @Juice113, 

Thanks for the issue, 
The working paper version of the code was in a separate branch, but I understand that it can be confusing, so we changed the main branch to contain the paper version code. Please clone again and try to install the packages using the `requirements.txt`, with
```
pip install -r requirements.txt
```
Let me know if it will work.

**Comment by Juice113** [comment]
Hi @bezirganyan , That helps a lot! i'm running the code successfully. Thank you for your quick reply!😊
<img width="601" alt="微信图片_20240222231232" src="https://github.com/bezirganyan/m2-mixer/assets/106001615/5c2b0547-a20a-450b-829d-a67af592b9f4">
